DSFacyt\Core\Domain\Model\Entity\Channel:
    type: entity
    table: channel
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string

        description:
            type: string

        status:
            type: string

    lifecycleCallbacks: {  }
