DSFacyt\Core\Domain\Model\Entity\Document:
    type: entity
    table: document
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbDocumentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        fileName:
            type: string

    oneToMany:
        images:
            targetEntity: Image
            mappedBy: document
            cascade: []
        videos:
            targetEntity: Video
            mappedBy: documet

    lifecycleCallbacks: {  }
