DSFacyt\Core\Domain\Model\Entity\Image:
    type: entity
    table: image
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: date

        end_date:
            type: date

        publish_time:
            type: time

        title:
            type: string

        description:
            type: string

        status:
            type: string

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: 
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false
        document:
            targetEntity: Document
            cascade: {  }
            mappedBy: null
            inversedBy: images
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: images
            inversedBy: null
            joinTable: null
            orderBy: null

    lifecycleCallbacks: {  }
