DSFacyt\Core\Domain\Model\Entity\QuickNote: 
    type: entity
    table: quick_note
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbQuickNoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: date

        end_date:
            type: date

        title:
            type: string

        info:
            type: string

        status:
            type: string

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: quick_notes
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: null
            inversedBy: quick_notes
            joinTable:
                name: channel_quick_note
                joinColumns:
                    -
                        name: quick_note_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: channel_id
                        referencedColumnName: id
            orderBy: null

    lifecycleCallbacks: {  }
