DSFacyt\Core\Domain\Model\Entity\Text: 
    type: entity
    table: text
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: date

        end_date:
            type: date

        publish_time:
            type: time

        title:
            type: string

        info:
            type: string

        status:
            type: string
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: texts
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false
        channel:
            targetEntity: Channel
            cascade: {  }
            mappedBy: null
            inversedBy: texts
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: texts
            inversedBy: null
            joinTable: null
            orderBy: null

    lifecycleCallbacks: {  }
