DSFacyt\Core\Domain\Model\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbUserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        last_name:
            type: string

        indentity_card:
            type: integer

        name:
            type: string

        phone:
            type: string

    oneToMany:
        images:
            targetEntity: Image
            mappedBy: user
        quick_notes:
            targetEntity: QuickNote
            mappedBy: user
        texts:
            targetEntity: Text
            mappedBy: user
        videos:
            targetEntity: Video
            mappedBy: user

    manyToOne:
        school:
            targetEntity: School
            cascade: {  }
            mappedBy: null
            inversedBy: users
            joinColumns:
                school_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
