DSFacyt\Core\Domain\Model\Entity\Video:
    type: entity
    table: video
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbVideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: date

        end_date:
            type: date

        publish_time:
            type: time

        title:
            type: string

        description:
            type: string

        status:
            type: string

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: videos
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        document:
            targetEntity: Document
            cascade: {  }
            mappedBy: null
            inversedBy: videos
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: null
            inversedBy: videos
            joinTable:
                name: channel_video
                joinColumns:
                    -
                        name: video_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: channel_id
                        referencedColumnName: id
            orderBy: null

    lifecycleCallbacks: {  }
