ds_facyt_admin_check_notifications:
    path: /check
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Notification:check"}
    options:
        expose: true

ds_facyt_admin_home_notification:
    path: /
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Notification:index" }
