# Los archivos de routing de la seguridad del modulo de administrador
ds_facyt_infrastructure_admin_module_security:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/security/security.yml"

# Rutas del modulo de publicaciones del administrador
ds_facyt_infrastructure_admin_module_publish:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/publish/routing.yml"
    prefix: /publish

# Rutas del modulo de canales del sistema
ds_facyt_infrastructure_admin_module_channel:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/channel.yml"
    prefix: /channel

# Modulo de notas rapidas
ds_facyt_infrastructure_quicknote:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/quicknote.yml"
    prefix:   /quicknote

# Rutas del modulo de usuarios del sistema
ds_facyt_infrastructure_admin_module_user:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/user.yml"
    prefix: /user

# Rutas del modulo de grupos del sistema
ds_facyt_infrastructure_admin_module_group:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/group.yml"
    prefix: /group

ds_facyt_infrastructure_admin_homepage:
    path:    /
    defaults: { _controller: DSFacytInfrastructureBundle:Admin\Default:index }

