DSFacyt\InfrastructureBundle\Entity\Channel:
    type: entity
    table: channel
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbChannelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string

        description:
            type: string

        status:
            type: integer   

    manyToMany:
        images:
            targetEntity: Image
            cascade: {  }
            mappedBy: channels
            inversedBy: null
            joinTable: null
            orderBy: null

        quick_notes:
            targetEntity: QuickNote
            cascade: {  }
            mappedBy: channels
            inversedBy: null
            joinTable: null
            orderBy: null

        texts:
            targetEntity: Text
            cascade: {  }
            mappedBy: channels
            inversedBy: null
            joinTable: null
            orderBy: null

        videos:
            targetEntity: Video
            cascade: {  }
            mappedBy: channels
            inversedBy: null
            joinTable: null
            orderBy: null

    lifecycleCallbacks: {  }
