DSFacyt\InfrastructureBundle\Entity\QuickNote:
    type: entity
    table: quick_note
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbQuickNoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        title:
            type: string

        info:
            type: string

        status:
            type: integer
            options:
                default: 1
        date_create:
            type: datetime
            nullable: true
        last_modified:
            type: datetime
            nullable: true

    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: null
            inversedBy: quick_notes
            joinTable:
                name: channel_quick_note
                joinColumns:
                    -
                        name: quick_note_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: channel_id
                        referencedColumnName: id
            orderBy: null

    lifecycleCallbacks: 
        prePersist: [updateLastModified]
        preUpdate: [updateLastModified]

