DSFacyt\InfrastructureBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbUserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        last_name:
            type: string
            nullable: true
            options:
                default: null

        indentity_card:
            type: integer
            nullable: true
            options:
                default: null

        name:
            type: string
            nullable: true
            options:
                default: null

        phone:
            type: string
            nullable: true
            options:
                default: null
        access:
            type: json_array
            nullable: true

    oneToOne:
        image_profile:
            targetEntity: Document
            inversedBy: user_image_profile
            joinColumn:
                name: image_profile_id
                referencedColumnName: id
            cascade: ["persist"]
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: user
        quick_notes:
            targetEntity: QuickNote
            mappedBy: user
        texts:
            targetEntity: Text
            mappedBy: user
        videos:
            targetEntity: Video
            mappedBy: user

    manyToOne:
        school:
            targetEntity: School
            cascade: {  }
            mappedBy: null
            inversedBy: users
            joinColumns:
                school_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToMany:
        groups:
            targetEntity: Group
            cascade: {  }
            mappedBy: null
            inversedBy: users
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

    lifecycleCallbacks:

        prePersist: [setDefaultAccess]
