DSFacyt\InfrastructureBundle\Entity\Video:
    type: entity
    table: video
    repositoryClass: DSFacyt\InfrastructureBundle\Repositories\DbVideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_date:
            type: date

        end_date:
            type: date

        publish_time:
            type: string

        title:
            type: string

        description:
            type: string

        status:
            type: integer
            options:
                default: 0
        date_create:
            type: datetime
            nullable: true

        important:
            type: boolean
            options:
                default: false
        last_modified:
            type: datetime
            nullable: true
        active:
            type: boolean
            options:
                default: true

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: videos
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        document:
            targetEntity: Document
            cascade: ["persist"]
            mappedBy: null
            inversedBy: videos
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToMany:
        channels:
            targetEntity: Channel
            cascade: {  }
            mappedBy: null
            inversedBy: videos
            joinTable:
                name: channel_video
                joinColumns:
                    -
                        name: video_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: channel_id
                        referencedColumnName: id
            orderBy: null

    lifecycleCallbacks:
        prePersist: [updateLastModified]
        preUpdate: [updateLastModified]