# Crear texto
ds_facyt_infrastructure_admin_new_image:
    path: /new
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:newText" }
    options:
        expose: true

# Validar texto Nuevo
ds_facyt_infrastructure_admin_image_new_validate:
    path: /newValidate
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:validateText" }
    options:
        expose: true

# Editar un texto
ds_facyt_infrastructure_admin_edit_image:
    path: /edit/{textId}
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:editText" }
    options:
        expose: true

ds_facyt_infrastructure_admin_text_image_validate:
  path: /text/{textId}/validate
  defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:validateEdit"}

