# Ruta de destacar una publición
ds_facyt_infrastructure_admin_update_important:
  path: /update/important
  defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:updateImportant"}
  options:
      expose: true
  requirements:
      { _format: (xml |json), _method: POST }

# Ruta de elimincación de una publicación
ds_facyt_infrastructure_admin_publish_delete:
  path: /delete
  defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:deletePublish"}
  options:
      expose: true
  requirements:
      { _format: (xml |json), _method: POST }

# Obtiene las publicaciones vía asincrona dado un tipo y un estado
ds_facyt_infrastructure_api_get_publish_type_status:
  path: /getPublish/async
  defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:apiGetPublishStatus"}
  options:
      expose: true
  requirements:
      { _format: (xml |json), _method: POST }

# Modulo de CRUD de los textos del sistema
ds_facyt_infrastructure_admin_module_publish_text:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/publish/text.yml"
    prefix: /text

# Modulo de CRUD de las imagenes del sistema
ds_facyt_infrastructure_admin_module_publish_image:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/publish/image.yml"
    prefix: /image

# Obtener una publicación dado un estado y un tipo de la publicación
ds_facyt_infrastructure_get_publish_type_status:
    path: /{type}/{status}
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:getPublishStatus", status: 0}
    options:
      expose: true  