# Crear texto
ds_facyt_infrastructure_admin_new_text:
    path: /new
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:newText" }
    options:
        expose: true

# Validar texto Nuevo
ds_facyt_infrastructure_admin_text_new_validate:
    path: /newValidate
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:validateText" }
    options:
        expose: true

# Editar un texto
ds_facyt_infrastructure_admin_edit_text:
    path: /edit/{textId}
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:editText" }
    options:
        expose: true