ds_facyt_infrastructure_admin_new_video:
    path: /new
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:newVideo" }
    options:
        expose: true

ds_facyt_infrastructure_admin_video_new_validate:
    path: /new_validate/{videoId}
    defaults: { _controller: DSFacytInfrastructureBundle:Admin\Publish:validateNewVideo, videoId: null }

ds_facyt_infrastructure_admin_edit_video:
    path:   /edit/{videoId}
    defaults: { _controller: DSFacytInfrastructureBundle:Admin\Publish:editVideo }
    options:
      expose: true