ds_facyt_infrastructure_admin_new_video:
    path: /new
    defaults: { _controller: "DSFacytInfrastructureBundle:Admin/Publish:newVideo" }
    options:
        expose: true

ds_facyt_infrastructure_admin_video_new_validate:
    path: /new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:Admin\Publish:validateNewVideo }