ds_facyt_infrastructure_user_image_homepage:
    path:   /image/{page}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:index , page : 1 }
    requirements:
        page: "\d+"
    options:
        expose: true

ds_facyt_infrastructure_user_image_new:
    path:   /image/new
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:publishNew }

ds_facyt_infrastructure_user_image_new_validate:
    path:   /image/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:validateNew }

#La ruta de eliminar un imagen
ds_facyt_infrastructure_user_image_delete:
    path:   /image/delete
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:delete }
    options:
      expose: true
    requirements:
      { _format: (xml | json), _method: POST}