ds_facyt_infrastructure_user_image_homepage:
    path:   /panel/image
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:index }

ds_facyt_infrastructure_user_image_new:
    path:   /panel/image/new
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:publishNew }

ds_facyt_infrastructure_user_image_new_validate:
    path:   /panel/image/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:validateNew }