ds_facyt_infrastructure_user_image_homepage:
    path:   /image/{page}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:index , page : 1 }
    requirements:
        page: "\d+"
    options:
        expose: true

ds_facyt_infrastructure_user_image_new:
    path:   /image/new
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:publishNew }

ds_facyt_infrastructure_user_image_new_validate:
    path:   /image/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:validateNew }

ds_facyt_infrastructure_user_image_edit:
  path:   /image/edit/{imageId}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Image:edit }
  options:
    expose: true

#La ruta de validación de una imagen previamente editado
ds_facyt_infrastructure_user_image_edit_validate:
    path:   /image/edit_validate/{imageId}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:validateEdit }


#La ruta de eliminar un imagen
ds_facyt_infrastructure_user_image_delete:
    path:   /image/delete
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:delete }
    options:
      expose: true
    requirements:
      { _format: (xml | json), _method: POST}


ds_facyt_infrastructure_user_image_set:
    path: /image/set
    defaults: { _controller: DSFacytInfrastructureBundle:User\Image:setImage}
    options:
      expose: true
    requirements:
      { _format: json, _method: POST }