#Los archivos de routing referentes a la seguridad del sistema para los usuarios(login, login_check, loguot)
ds_facyt_infrastructure_user_module_security:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/security/security.yml"

# Rutas de gestion de textos publicado
ds_facyt_infrastructure_user_text:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/text.yml"

# Rutas de gestion de imágenes
ds_facyt_infrastructure_user_image:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/image.yml"

# Rutas de gestion de videos 
ds_facyt_infrastructure_user_video:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/video.yml"

ds_facyt_infrastructure_get_publish_async:
    path:   /publish/async
    defaults: { _controller: DSFacytInfrastructureBundle:Default:apiGetPublishStatus}
    options:
        expose: true

# Ruta de registrar un usuario
ds_facyt_infrastructure_register:
    path:    /register
    defaults: { _controller: DSFacytInfrastructureBundle:Default:register }

# Ruta de validación del proceso de registro
ds_facyt_infrastructure_validate_register:
    path:   /register/validate
    defaults: { _controller: DSFacytInfrastructureBundle:Default:registerValidation}

# Rutas de gestion de textos publicado
ds_facyt_infrastructure_user_homepage:
    path:   /
    defaults: { _controller: DSFacytInfrastructureBundle:User\Default:indexPanel }

# Ruta trae los datos de el usuario
ds_facyt_infrastructure_user_profile:
    path:   /profile
    defaults: { _controller: DSFacytInfrastructureBundle:User\Default:getProfile }
    options:
        expose: true

ds_facyt_infrastructure_user_edit_profile:
    path:   /profile/edit
    defaults:   { _controller: DSFacytInfrastructureBundle:User\Default:editProfile }
    options:
        expose: true
    requirements:
        { _format: (xml | json), _method: POST}

ds_facyt_infrastructure_user_upload_image:
    path:   /profile/uploadImage
    defaults: { _controller: DSFacytInfrastructureBundle:User\Default:uploadImage }
    options:
        expose: true
    requirements:
        { _method: POST }