ds_facyt_infrastructure_user_text_homepage:
  path:   /panel/text
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:index }

ds_facyt_infrastructure_user_text_new:
  path:   /panel/text/new
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:publishNew }