#La siguiente ruta obtiene el lista de los textos publicados dado una paginaci贸n
ds_facyt_infrastructure_user_text_homepage:
  path:   /text/{page}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:index, page : 1 }
  requirements:
      page: "\d+"
  options:
      expose: true

#La siguiente ruta de crear un texto nuevo
ds_facyt_infrastructure_user_text_new:
  path:   /text/new
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:publishNew }

#La siguiente ruta en donde se validan los datos de creaci贸n de un texto nuevo
ds_facyt_infrastructure_user_text_new_validate:
    path:   /text/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:validateNew }

#La ruta de edici贸n de un texto publicado
ds_facyt_infrastructure_user_text_edit:
  path:   /text/edit/{textId}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:edit }
  options:
    expose: true

#La ruta de validaci贸n de un texto previamente editado
ds_facyt_infrastructure_user_text_edit_validate:
    path:   /text/edit_validate/{textId}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:validateEdit }


#La ruta de eliminar un texto 
ds_facyt_infrastructure_user_text_delete:
    path:   /text/delete
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:delete }
    options:
      expose: true
    requirements:
      { _format: (xml | json), _method: POST}


ds_facyt_infrastructure_user_text_set:
    path: /text/set
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:setText}
    options:
      expose: true
    requirements:
      { _format: json, _method: POST }