ds_facyt_infrastructure_user_text_homepage:
  path:   /panel/text/{page}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:index, page : 1 }
  options:
      expose: true

ds_facyt_infrastructure_user_text_new:
  path:   /panel/text/new
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:publishNew }

ds_facyt_infrastructure_user_text_new_validate:
    path:   /panel/text/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:validateNew }

ds_facyt_infrastructure_user_text_edit:
  path:   /panel/text/edit/{textId}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Text:edit }

ds_facyt_infrastructure_user_text_edit_validate:
    path:   /panel/text/edit_validate/{textId}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:validateEdit }

ds_facyt_infrastructure_user_text_delete:
    path:   /panel/text/delete
    defaults: { _controller: DSFacytInfrastructureBundle:User\Text:delete }
    options:
      expose: true
    requirements:
      { _format: (xml | json), _method: POST}

