ds_facyt_infrastructure_user_video_homepage:
  path:   /video/{page}
  defaults: { _controller: DSFacytInfrastructureBundle:User\Video:index , page : 1 }
  requirements:
    page: "\d+"
  options:
    expose: true


ds_facyt_infrastructure_user_video_new:
  path:   /video/new
  defaults: { _controller: DSFacytInfrastructureBundle:User\Video:publishNew }


ds_facyt_infrastructure_user_video_new_validate:
    path:   /video/new_validate
    defaults: { _controller: DSFacytInfrastructureBundle:User\Video:validateNew }

ds_facyt_infrastructure_user_video_edit:
    path:   /video/edit/{videoId}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Video:edit }
    options:
      expose: true

#La ruta de validación de una videon previamente editado
ds_facyt_infrastructure_user_video_edit_validate:
    path:   /video/edit_validate/{videoId}
    defaults: { _controller: DSFacytInfrastructureBundle:User\Video:validateEdit }

ds_facyt_infrastructure_user_video_set:
    path: /video/set
    defaults: { _controller: DSFacytInfrastructureBundle:User\Video:setVideo}
    options:
      expose: true
    requirements:
      { _format: json, _method: POST }