security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: ds_facyt_infrastructure_user_security_login
                check_path: ds_facyt_infrastructure_user_security_check
                default_target_path: ds_facyt_infrastructure_user_homepage
            logout: 
                path:   ds_facyt_infrastructure_user_security_logout
                target: ds_facyt_infrastructure_user_security_login
            anonymous: true
    #Seguridad del usuarios
        user:
            pattern: ^/%extension_user%
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: ds_facyt_infrastructure_user_security_login
                check_path: ds_facyt_infrastructure_user_security_check
                default_target_path: ds_facyt_infrastructure_user_homepage
            logout: 
                path:   ds_facyt_infrastructure_user_security_logout
                target: ds_facyt_infrastructure_user_security_login
            anonymous: true
    #Seguridad del administrador
        admin:
            pattern: ^/%extension_admin%
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: ds_facyt_infrastructure_admin_security_login
                check_path: ds_facyt_infrastructure_admin_security_check
                default_target_path: ds_facyt_infrastructure_admin_homepage
            logout: 
                path:   ds_facyt_infrastructure_admin_security_logout
                target: ds_facyt_infrastructure_admin_security_login
            anonymous: true

    access_control:

        # Rutas de acceso a todos los usuarios
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Rutas de acceso de los usuarios registrados
        - { path: ^/%extension_user%/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%extension_user%/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%extension_user%, role: ROLE_USER }

        # Rutas de acceso del administrador
        - { path: ^/%extension_admin%/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%extension_admin%/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%extension_admin%, role: ROLE_ADMIN }
