# ====RUTAS DE MODULOS DE USUARIOS (ADMIN /  USUARIOS DEL SISTEMA) ===

# Las rutas referentes a los usuarios registrados
ds_facyt_infrastructure_module_user:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/routing.yml"
    prefix: "{extension}"
    requirements:
        extension: "%extension_user%"
    defaults:
        extension: "%extension_user%"

# Rutas del administrador
ds_facyt_infrastructure_module_admin:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/routing.yml"
    prefix: "{extension}"
    requirements:
        extension: %extension_admin%
    defaults:
        extension: "%extension_admin%"
# Rutas de vista de las pantallas
ds_facyt_infrastructure_module_display:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/display/routing.yml"
    prefix: "display"

# === RUTAS DE MODULOS DE USUARIOS  INVITADOS ===

# HomePage del sistema
ds_facyt_infrastructure_homepage:
    path:    /
    defaults: { _controller: DSFacytInfrastructureBundle:Default:index }
