# ====RUTAS DE MODULOS DE USUARIOS (ADMIN /  USUARIOS DEL SISTEMA) ===

# Las rutas referentes a los usuarios registrados
ds_facyt_infrastructure_module_user:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/user/routing.yml"
    prefix: "{extension}"
    requirements:
        extension: "%extension_user%"
    defaults:
        extension: "%extension_user%"

ds_facyt_infrastructure_module_admin:
    resource: "@DSFacytInfrastructureBundle/Resources/config/routing/admin/routing.yml"
    prefix: "{extension}"
    requirements:
        extension: %extension_admin%
    defaults:
        extension: "%extension_admin%"

# === RUTAS DE MODULOS DE USUARIOS  INVITADOS ===

# HomePage del sistema
ds_facyt_infrastructure_homepage:
    path:    /
    defaults: { _controller: DSFacytInfrastructureBundle:Default:index }

# Ruta de registrar un usuario
ds_facyt_infrastructure_register:
    path:    /register
    defaults: { _controller: DSFacytInfrastructureBundle:Default:register }

# Ruta de validación del proceso de registro
ds_facyt_infrastructure_validate_register:
    path:   /register/validate
    defaults: { _controller: DSFacytInfrastructureBundle:Default:registerValidation}