services:

#Servicios de Infraestructura
    RepositoryFactory:
        class: DSFacyt\InfrastructureBundle\Resources\Services\RepositoryFactory
        arguments: ["@doctrine.orm.entity_manager"]

#Servicios de la Aplicación
    CommandBus:
        class: DSFacyt\Core\Application\Services\CommandBus
        arguments: ["@RepositoryFactory"]