services:

#Servicios de Infraestructura
    RepositoryFactory:
        class: DSFacyt\InfrastructureBundle\Resources\Services\RepositoryFactory
        arguments: ["@doctrine.orm.entity_manager"]

    Pagination:
        class: DSFacyt\InfrastructureBundle\Resources\Services\Pagination
        arguments: ["@service_container"]

    app.twig_extension:
        class: DSFacyt\InfrastructureBundle\Resources\Services\TwigExtension
        arguments: ["@service_container"]
        public: false
        tags:
            - { name: twig.extension }

#Servicios de la Aplicación
    CommandBus:
        class: DSFacyt\Core\Application\Services\CommandBus
        arguments: ["@RepositoryFactory","@Pagination"]

    EmailService:
        class: DSFacyt\InfrastructureBundle\Resources\Services\EmailService
        arguments: ["@service_container"]