channel:
    path:     /
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:index" }

channel_show:
    path:     /{id}/show
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:show" }

channel_new:
    path:     /new
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:new" }

channel_create:
    path:     /create
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:create" }
    methods:  POST

channel_edit:
    path:     /{id}/edit
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:edit" }

channel_update:
    path:     /{id}/update
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:update" }
    methods:  [POST, PUT]

channel_delete:
    path:     /{id}/delete
    defaults: { _controller: "DSFacytInfrastructureBundle:Channel:delete" }
    methods:  [POST, DELETE]
